name: selleasy
description: "Ứng dụng quản lý doanh nghiệp - Quản lý đơn hàng, sản phẩm và khách hàng một cách dễ dàng"
publish_to: 'none'
version: 1.0.2+16

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.8.3
  provider: ^6.1.1
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.7
  csv: ^5.1.1
  path_provider: ^2.1.5
  http: ^1.2.0
  intl: ^0.19.0
  fl_chart: 0.63.0
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.2.5
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.3.0+17
  in_app_purchase_storekit: ^0.3.8+1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"